/** Default work categories seeded into the database. Admins can add/edit more from the app. */
export const DEFAULT_CATEGORIES: { slug: string; name: string; nameBn: string; icon: string }[] = [
  { slug: "daily-labor", name: "Daily Labor", nameBn: "দিনমজুর", icon: "hammer" },
  { slug: "construction", name: "Construction & Mason", nameBn: "রাজমিস্ত্রি", icon: "construct" },
  { slug: "electrician", name: "Electrician", nameBn: "ইলেকট্রিশিয়ান", icon: "flash" },
  { slug: "plumber", name: "Plumber", nameBn: "প্লাম্বার", icon: "water" },
  { slug: "carpenter", name: "Carpenter", nameBn: "কাঠমিস্ত্রি", icon: "cube" },
  { slug: "painter", name: "Painter", nameBn: "রংমিস্ত্রি", icon: "color-palette" },
  { slug: "cleaning", name: "Cleaning & Housekeeping", nameBn: "পরিচ্ছন্নতা কর্মী", icon: "sparkles" },
  { slug: "cook", name: "Cook", nameBn: "রাঁধুনি", icon: "restaurant" },
  { slug: "driver", name: "Driver", nameBn: "ড্রাইভার", icon: "car" },
  { slug: "moving-helper", name: "Moving & Shifting", nameBn: "বাসা বদল সহকারী", icon: "cube-outline" },
  { slug: "porter", name: "Porter & Loading", nameBn: "কুলি / লোড-আনলোড", icon: "barbell" },
  { slug: "security-guard", name: "Security Guard", nameBn: "নিরাপত্তা প্রহরী", icon: "shield-checkmark" },
  { slug: "gardener", name: "Gardener", nameBn: "মালি", icon: "leaf" },
  { slug: "farm-worker", name: "Farm Worker", nameBn: "কৃষি শ্রমিক", icon: "nutrition" },
  { slug: "delivery", name: "Delivery", nameBn: "ডেলিভারি", icon: "bicycle" },
  { slug: "tailor", name: "Tailor", nameBn: "দর্জি", icon: "cut" },
  { slug: "mechanic", name: "Mechanic", nameBn: "মেকানিক", icon: "build" },
  { slug: "welder", name: "Welder", nameBn: "ওয়েল্ডার", icon: "flame" },
  { slug: "ac-technician", name: "AC & Appliance Technician", nameBn: "এসি টেকনিশিয়ান", icon: "snow" },
  { slug: "caregiver", name: "Caregiver & Babysitter", nameBn: "কেয়ারগিভার", icon: "heart" },
  { slug: "tiles-fitter", name: "Tiles & Floor Fitter", nameBn: "টাইলস মিস্ত্রি", icon: "grid" },
  { slug: "event-helper", name: "Event Helper", nameBn: "অনুষ্ঠান সহকারী", icon: "people" },
];
